package com.voiceguard.rules

import com.voiceguard.domain.context.ConversationContext
import com.voiceguard.domain.dsp.Fft
import com.voiceguard.domain.dsp.PitchAnalysis
import com.voiceguard.domain.model.AudioChunk
import com.voiceguard.domain.model.RuleResult
import com.voiceguard.domain.port.AudioDetectionRule
import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.sqrt

/**
 * VG-020 — Detects unnaturally stable harmonic structures generated by vocoders.
 *
 * Natural voiced speech has micro-instabilities in its harmonic comb: partials drift slightly
 * in frequency and amplitude across glottal cycles due to nonlinear vocal-tract dynamics and
 * subglottal coupling. Vocoders synthesize harmonics as near-perfect sinusoids at exact multiples
 * of the fundamental, producing a remarkably stable spectral shape chunk-to-chunk.
 *
 * This rule tracks cosine similarity between successive magnitude spectra (voiced frames only,
 * Hann-windowed, limited to the harmonic range up to [MAX_HARMONIC_HZ]). High cross-chunk
 * similarity → high suspicion.
 *
 * Direction note: the AUC of this rule on the FoR dataset should be validated. If the direction
 * is inverted (FoR TTS is more spectrally variable than flat human reads), a wrapper rule or
 * [invertDirection] flag may be needed — see [ProsodicDynamicsRule] for precedent.
 */
class HarmonicConsistencyRule(
    private val fftSize: Int = DEFAULT_FFT_SIZE,
    override val weight: Float = 0.50f
) : AudioDetectionRule {

    override val name = "HarmonicConsistencyRule"
    override val isHeavyAnalysis = true

    private var voicedChunks = 0
    private var previousSpectrum: FloatArray? = null
    private val similarities = ArrayList<Float>()

    override suspend fun analyze(chunk: AudioChunk, context: ConversationContext): RuleResult {
        val pitch = PitchAnalysis.estimatePitch(chunk.pcmData, chunk.sampleRate)
        if (!pitch.isVoiced || pitch.voicingStrength < VOICING_THRESHOLD) return RuleResult(0f, 0f)

        val spectrum = computeHarmonicSpectrum(chunk.pcmData, chunk.sampleRate)
        val prev = previousSpectrum
        if (prev != null && prev.size == spectrum.size) {
            similarities.add(cosineSimilarity(prev, spectrum))
        }
        previousSpectrum = spectrum
        voicedChunks++

        if (voicedChunks < MIN_VOICED_CHUNKS || similarities.isEmpty()) return RuleResult(0f, 0f)

        val confidence = (voicedChunks.toFloat() / RAMP_CHUNKS).coerceAtMost(1f)
        val meanSimilarity = similarities.average().toFloat()

        // Cosine similarity in [0, 1]; values above ORGANIC_FLOOR are suspiciously stable.
        val suspicion = ((meanSimilarity - ORGANIC_SIMILARITY_FLOOR) /
            (1f - ORGANIC_SIMILARITY_FLOOR)).coerceIn(0f, 1f)

        return RuleResult(suspicion, confidence)
    }

    /**
     * Hann-windowed magnitude spectrum truncated to the harmonic range [0, MAX_HARMONIC_HZ].
     */
    private fun computeHarmonicSpectrum(samples: FloatArray, sampleRate: Int): FloatArray {
        val windowed = FloatArray(fftSize) { i ->
            val s = if (i < samples.size) samples[i] else 0f
            val w = 0.5f * (1f - cos(2.0 * PI * i / (fftSize - 1))).toFloat()
            s * w
        }
        val mag = Fft.magnitudeSpectrum(windowed)
        val nyquist = sampleRate / 2f
        val cutoffBin = (mag.size * MAX_HARMONIC_HZ / nyquist).toInt().coerceIn(1, mag.size)
        return mag.copyOf(cutoffBin)
    }

    private fun cosineSimilarity(a: FloatArray, b: FloatArray): Float {
        var dot = 0.0; var normA = 0.0; var normB = 0.0
        for (i in a.indices) {
            dot += a[i] * b[i]; normA += a[i] * a[i]; normB += b[i] * b[i]
        }
        if (normA == 0.0 || normB == 0.0) return 0f
        return (dot / (sqrt(normA) * sqrt(normB))).toFloat().coerceIn(0f, 1f)
    }

    companion object {
        private const val DEFAULT_FFT_SIZE = 2048
        private const val MIN_VOICED_CHUNKS = 2
        private const val RAMP_CHUNKS = 6
        private const val VOICING_THRESHOLD = 0.4f
        private const val MAX_HARMONIC_HZ = 4000f

        // Cross-chunk cosine similarity below this value is considered organically variable.
        // Above this threshold, the harmonic structure is suspiciously stable (vocoder-like).
        private const val ORGANIC_SIMILARITY_FLOOR = 0.80f
    }
}
